[[redirects]]
  from = "/*"
# FIXME: we should still use a function so this works from browsers too, and redirects to an MSI for Windows
  to = "https://raw.githubusercontent.com/volta-cli/volta/master/dev/unix/volta-install.sh"
  status = 302
